#!/usr/bin/env bash
# Day-1 chunked annotation run (2026-09-06) — docs/superpowers/specs/2026-09-06-day1-chunked-run-design.md
#
# Runs EVERY step except the VLM check over each chunk of the 2026-09-04 Dhaka
# capture (Dataset/A_nusc/chunk_NNNN), one chunk at a time, and for each chunk
# leaves behind:
#   export/day1_chunk_NNNN/boxes/     nuScenes-format release, every blob a REAL
#                                     FILE (export_release --blobs copy)
#   export/day1_chunk_NNNN/lidarseg/  road-surface lidarseg layer (tables + .bin;
#                                     the blobs are already real files in boxes/)
#   CVAT projects "day1_chunk_NNNN (2D)", "(3D)", "(road)" on $CVAT_HOST
#
# Per-chunk ISOLATION: each chunk gets its own generated paths config and its
# own work/out roots under /home/mt/dhakascenes/{work,out,probe_out}_day1/, so
# no chunk's stage tree is overwritten by the next and any chunk can be resumed
# or republished alone with the wrapper and that chunk's config.
#
# What does NOT run, and why (substrate, not choice):
#   3b   walks 12 Hz sweep frames; this export has ONE image per keyframe.
#   3c   the operator's one exclusion; VLM_CHECK/VLM_USE_CHECKED default 0.
#   The GT halves of `eval` are soft and no-op: there is no sample_annotation.
# Road runs DEGRADED (its ZED refinement keys on rings 10/11; this export
# carries ZED as ring 100+k) — the nuScenes precedent, _SUCCESS.degraded.
#
# Usage:
#   scripts/run_day1_chunks.sh                 # 0006 first (calibration), then 0000..0005
#   scripts/run_day1_chunks.sh 0006            # one chunk
#   scripts/run_day1_chunks.sh 0000 0001       # these, in this order
#   DRY_RUN=1 scripts/run_day1_chunks.sh 0006  # write the config, print the wrapper's plan, run nothing
#
# The CVAT purge is NOT here. It is a one-way door and was run by hand, once,
# before the first chunk (scripts/cvat_purge.py --yes).

set -uo pipefail

REPO=/home/mt/Zami/Annotation_pipeline
DATASET=$REPO/Dataset/A_nusc
EXPORT=$REPO/export
ROOT_WORK=/home/mt/dhakascenes/work_day1
ROOT_OUT=/home/mt/dhakascenes/out_day1
ROOT_PROBE=/home/mt/dhakascenes/probe_out_day1
LOGS=$ROOT_WORK/logs
PY=/home/mt/miniconda3/envs/ano_pipe/bin/python
VERSION=v1.0-dhaka          # the version dir inside every chunk, verbatim (read-only)
# The chain runs against a FIXED sibling version: ~5 % of keyframes lack a
# camera image and Stage 0's channels_complete is all-or-nothing per scene.
# scripts/fixup_a_nusc.py drops those samples into $VERSION-fixed beside the
# original (the pilot's v1.0-dhaka-fixed precedent); written once per chunk.
FIXED_VERSION=$VERSION-fixed
# Camera streams the exporter filed under each other's names (see the fixup
# call). Empty = no swap.
SWAP_CHANNELS=${SWAP_CHANNELS-CAM_LEFT CAM_RIGHT}
DAY=day1
# Host side of the CVAT share: `docker volume inspect cvat_cvat_share` -> bind of
# /home/mt/Zami/nuscenes (a symlink into this repo's nuscenes/). Chunks are
# staged under $CVAT_SHARE_ROOT/day1_chunk_NNNN/samples as hard links.
CVAT_SHARE_ROOT=${CVAT_SHARE_ROOT:-/home/mt/Zami/nuscenes}

# Everything but 3b/3c — INCLUDING arm B (3f: the RSUD20K-finetuned detector
# that knows rickshaws and CNGs; 3m: the vocabulary-authority merge, C28/C34),
# which the first calibration run omitted (operator, 2026-09-06 01:55: "did
# you not run the custom rickshaw and CNG class?"). Typed order is execution
# order (run_stages.sh never sorts): arm A, arm B, merge, then the GPU box
# chain on the merged tree, road (consumes Stage 1 alone), the COCO export +
# renders, then the three publishes.
CHAIN_STEPS=${CHAIN_STEPS:-"0 1 3 3f 3m 4 5 6 7 8 road eval viz cvat cvat3d cvatroad"}

DEFAULT_ORDER=(0006 0000 0001 0002 0003 0004 0005)
CHUNKS=("$@")
[ ${#CHUNKS[@]} -eq 0 ] && CHUNKS=("${DEFAULT_ORDER[@]}")

cd "$REPO" || exit 2
mkdir -p "$LOGS" "$EXPORT"

# .env carries CVAT_PASSWORD and the cache roots. Sourced FIRST so that the
# per-chunk exports below win over anything it declares.
if [ -f .env ]; then set -a; . ./.env; set +a; fi
export DHAKASCENES_SUBSTRATE=dhaka6

say() { echo; echo "############ $* ############"; date; }

# run_stages.sh's exit code is a claim; the markers are the record (it exits 0
# on a degraded-but-complete chain and 1 on a refusal). Same reader as
# run_nuscenes_full.sh.
marker_state() {  # stage dir -> clean | degraded | none
  if   [ -e "$1/_SUCCESS" ];          then echo clean
  elif [ -e "$1/_SUCCESS.degraded" ]; then echo degraded
  else echo none
  fi
}

write_paths_config() {  # chunk id -> writes configs/paths_day1_chunk_NNNN.yaml, echoes its path
  local id=$1 cfg=configs/paths_${DAY}_chunk_$1.yaml
  cat > "$cfg" <<EOF
# GENERATED by scripts/run_day1_chunks.sh — the ${DAY} chunk_${id} path contract.
# Selected per run with DHAKASCENES_PATHS_CONFIG=$cfg (and DHAKASCENES_SUBSTRATE=dhaka6).
# Write roots are per-chunk and disjoint from every other substrate's (§1.8).
dataroot: $DATASET/chunk_$id
meta_root: $DATASET/chunk_$id
version: $FIXED_VERSION
work_root: $ROOT_WORK/chunk_$id
out_root: $ROOT_OUT/chunk_$id
probe_out_root: $ROOT_PROBE/chunk_$id
EOF
  echo "$cfg"
}

run_chunk() {  # chunk id -> 0 ok | 1 core chain failed | 2 export failed
  local id=$1 chunk=$DATASET/chunk_$1 name=${DAY}_chunk_$1
  # EXPORT_SUFFIX (e.g. "_vlm"): a rerun writes export/day1_chunk_NNNN_vlm/
  # beside the earlier export instead of replacing it, and its CVAT tasks land
  # beside the earlier ones under a new run tag (C30). Nothing already reviewed
  # is deleted — operator, 2026-09-06: "don't delete CVAT exports unless I say so".
  local work=$ROOT_WORK/chunk_$1 out=$EXPORT/${DAY}_chunk_$1${EXPORT_SUFFIX:-}
  local t0=$SECONDS

  say "CHUNK $id  ($name)"
  if [ ! -d "$chunk/samples" ] || [ ! -d "$chunk/$VERSION" ]; then
    echo "!!! $chunk is not a chunk root (no samples/ or $VERSION/). Skipping."; return 1
  fi
  # The validator wants sweeps/ present and readable; an empty dir satisfies
  # it. With the fixed version dir below, the only writes into the dataroot.
  mkdir -p "$chunk/sweeps"
  if [ ! -d "$chunk/$FIXED_VERSION" ]; then
    say "  [$id] fixup: $VERSION -> $FIXED_VERSION (drop keyframes missing a required channel)"
    # --swap-channels: the exporter filed the right-facing stream as CAM_LEFT
    # and the left-facing one as CAM_RIGHT (measured 2026-09-06 by rearward
    # image drift, +68.6 / -80.6 px; operator spotted the scrambled 3D boxes).
    "$PY" scripts/fixup_a_nusc.py --dataroot "$chunk" --version "$VERSION" --out-version "$FIXED_VERSION" \
      ${SWAP_CHANNELS:+--swap-channels $SWAP_CHANNELS}
    local fix_rc=$?
    if [ $fix_rc -ne 0 ]; then echo "!!! [$id] fixup failed rc=$fix_rc"; return 1; fi
  else
    echo "fixup   : $chunk/$FIXED_VERSION present, reused"
  fi

  local cfg; cfg=$(write_paths_config "$id")
  export DHAKASCENES_PATHS_CONFIG=$cfg
  export CVAT_PIPELINE_PROJECT="$name (2D)"
  export CVAT_PIPELINE_3D_PROJECT="$name (3D)"
  export CVAT_ROAD_PROJECT="$name (road)"
  # The 2D and road tasks are created FROM THE CVAT SHARE (no image bytes are
  # copied into CVAT): frame paths resolve against the docker bind at
  # $CVAT_SHARE_ROOT. It still holds pilot_1632's frames under the very same
  # relative names this export uses, and every day-1 chunk repeats those names
  # — so each chunk is staged under its own prefix, as HARD LINKS (same
  # filesystem: no copy, no symlink, nothing for the container to fail to
  # resolve), and the publish is told the prefix via CVAT_SHARE_PREFIX.
  if [ ! -d "$CVAT_SHARE_ROOT" ]; then echo "!!! CVAT share root $CVAT_SHARE_ROOT missing"; return 1; fi
  if [ ! -d "$CVAT_SHARE_ROOT/$name/samples" ]; then
    mkdir -p "$CVAT_SHARE_ROOT/$name" && cp -al "$chunk/samples" "$CVAT_SHARE_ROOT/$name/" \
      || { echo "!!! [$id] could not stage samples into the CVAT share"; return 1; }
    echo "share   : staged $(find "$CVAT_SHARE_ROOT/$name/samples" -type f | wc -l) hard links under $CVAT_SHARE_ROOT/$name/"
  else
    echo "share   : $CVAT_SHARE_ROOT/$name/samples present, reused"
  fi
  export CVAT_SHARE_PREFIX="$name/"
  echo "config  : $cfg"
  echo "work    : $work"
  echo "export  : $out"
  echo "cvat    : '$CVAT_PIPELINE_PROJECT' / '$CVAT_PIPELINE_3D_PROJECT' / '$CVAT_ROAD_PROJECT'"
  echo "steps   : $CHAIN_STEPS"
  # Stage 6 takes epsilon and Stage 8 takes class means from priors_pilot_v0.json
  # and both refuse one not bound to THIS dataroot's fingerprint. Dhaka has no
  # GT to derive it from; it is AUTHORED (handover §6 recipe as code) — after
  # the fixup, so the fingerprint is the fixed tables'. Idempotent.
  "$PY" scripts/author_priors_dhaka.py --paths "$cfg" || { echo "!!! [$id] priors authoring failed"; return 1; }

  if [ "${DRY_RUN:-0}" = 1 ]; then
    PRINT_STEPS=1 scripts/run_stages.sh $CHAIN_STEPS
    return 0
  fi
  if [ -d "$out/boxes/$FIXED_VERSION" ] && [ -n "$(ls -A "$out/boxes/$FIXED_VERSION" 2>/dev/null)" ]; then
    echo "!!! $out/boxes/$FIXED_VERSION already exists and is not empty — export_release would refuse."
    echo "!!! Remove it (or the whole $out) to re-export this chunk. Skipping."
    return 2
  fi

  # 1. The chain, publishes included (no --no-cvat).
  say "  [$id] 1/4 chain"
  local stamp; stamp=$(mktemp -p "$LOGS" ".chain_start_${id}_XXXX")
  scripts/run_stages.sh $CHAIN_STEPS
  local chain_rc=$?
  local s8; s8=$(marker_state "$work/stage8_inflate")
  local sr; sr=$(marker_state "$work/stage_road")
  echo "chain rc=$chain_rc   stage8_inflate=$s8   stage_road=$sr"
  # A marker is the record, but only THIS chain's record counts: a work tree
  # reused from an earlier run still holds that run's clean Stage 8 marker,
  # and on 2026-09-06 14:00 an aborted chain (3c refused) sailed past this
  # gate on it and exported the OLD run's boxes under the new run's name.
  if [ "$s8" = none ] || [ ! "$work/stage8_inflate/run_manifest.json" -nt "$stamp" ]; then
    rm -f "$stamp"
    echo "!!! [$id] no Stage 8 completed by THIS chain (marker=$s8, chain rc=$chain_rc) — nothing to gate, nothing to export."; return 1
  fi
  rm -f "$stamp"

  # 2. Stage 9 QA gate -> prelabels.jsonl (the only producer export_release reads).
  say "  [$id] 2/4 stage 9 QA gate"
  local acc=(); [ "$s8" = degraded ] && acc=(--accept-degraded-upstream)
  "$PY" -m pipeline.stage9_qa.gate --paths "$cfg" ${acc[@]+"${acc[@]}"}
  local gate_rc=$?
  echo "stage 9 rc=$gate_rc"
  if [ $gate_rc -ge 2 ]; then echo "!!! [$id] stage 9 REFUSED (rc=$gate_rc). No export."; return 2; fi

  # 3. THE DELIVERABLE — every blob a real file.
  say "  [$id] 3/4 export_release --blobs copy -> $out/boxes"
  mkdir -p "$out"
  "$PY" scripts/export_release.py \
    --prelabels "$work/stage9_qa" \
    --dataroot "$chunk" --version "$FIXED_VERSION" \
    --out "$out/boxes" \
    --mapper configs/release_category_map.yaml \
    --blobs copy
  local rel_rc=$?
  echo "export_release rc=$rel_rc"

  # 4. The EXTRAS — everything nuScenes has no notion of, each in its own
  #    named folder beside boxes/ (operator, 2026-09-06: "export what is
  #    compatible in nuScenes and put the extras in folders with appropriate
  #    names such as road").
  #    road/     road-surface layer as nuScenes-lidarseg tables + per-keyframe
  #              .bin masks. Without --link-blobs it writes no symlinks and no
  #              blob copies — the blobs are already real files in boxes/.
  #    coco_2d/  per-scene COCO: Stage 3 boxes + Stage 4 masks in image space,
  #              exactly what the CVAT 2D task received.
  local road_rc=99
  if [ "$sr" != none ]; then
    say "  [$id] 4/4 extras: road/ + coco_2d/"
    local racc=(); [ "$sr" = degraded ] && racc=(--accept-degraded-upstream)
    "$PY" -m scripts.export_road_lidarseg --paths "$cfg" --out "$out/road" ${racc[@]+"${racc[@]}"}
    road_rc=$?
    echo "export_road_lidarseg rc=$road_rc"
  else
    say "  [$id] 4/4 extras: coco_2d/ (road stage wrote no marker — no road/ layer; boxes unaffected)"
  fi
  if [ -d "$work/cvat_export" ]; then
    mkdir -p "$out/coco_2d" && cp -r "$work/cvat_export/." "$out/coco_2d/" && echo "coco_2d: $(ls "$out/coco_2d" | tr '\n' ' ')"
  fi
  cat > "$out/README.md" <<EOF
# $name — machine pre-annotations (no VLM check)

Produced $(date +%Y-%m-%dT%H:%M:%S%z) by scripts/run_day1_chunks.sh from Dataset/A_nusc/chunk_$id
(version $FIXED_VERSION: $VERSION with keyframes missing a required channel dropped).
Stage tree: $work

- boxes/    nuScenes v1.0-format release: the 13 tables under boxes/$FIXED_VERSION/ with
            sample_annotation/instance/category filled by the pipeline, and samples/ as
            REAL FILES (no symlinks). Load with nuscenes-devkit: NuScenes(version="$FIXED_VERSION", dataroot="boxes").
- road/     EXTRA, not part of stock nuScenes: road-surface layer as nuScenes-lidarseg
            tables + road/lidarseg/$FIXED_VERSION/<sample_data_token>_lidarseg.bin. Reads
            against boxes/samples/. Absent if the road stage wrote no marker.
- coco_2d/  EXTRA: per-scene COCO instances.json — 2D boxes + segmentation masks in image
            space (1280x720), the content of the CVAT 2D review task.

Provenance: every stage's run_manifest.json under the stage tree above; the
pipeline's own QA gate wrote boxes from prelabels.jsonl (Stage 9).
EOF

  # Disk: Stage 1's per-keyframe clouds are ~1.2 GB per 93 keyframes (two
  # copies — with w_acc_count=1 the accumulated cloud IS the single sweep) and
  # nothing downstream of this point reads them: the box release, the lidarseg
  # layer and the CVAT 3D archive are all on disk by now. Pruned by default so
  # six chunks fit; PRUNE_CLOUDS=0 keeps them (re-running Stage 5/6/road on
  # this chunk then needs no Stage 1 rerun).
  if [ "${PRUNE_CLOUDS:-1}" = 1 ] && [ $rel_rc -eq 0 ] && [ -d "$work/stage1_ingestion/clouds" ]; then
    local freed; freed=$(du -sh "$work/stage1_ingestion/clouds" 2>/dev/null | cut -f1)
    rm -rf "$work/stage1_ingestion/clouds" && echo "pruned  : $work/stage1_ingestion/clouds ($freed) — exports are on disk; PRUNE_CLOUDS=0 to keep"
  fi

  local n_links; n_links=$(find "$out" -type l 2>/dev/null | wc -l)
  local n_files; n_files=$(find "$out" -type f 2>/dev/null | wc -l)
  local sz; sz=$(du -sh "$out" 2>/dev/null | cut -f1)
  local mins=$(( (SECONDS - t0) / 60 ))
  echo
  echo "=== CHUNK $id SUMMARY: chain rc=$chain_rc (s8=$s8, road=$sr) gate=$gate_rc release=$rel_rc lidarseg=$road_rc | export: $n_files files, $n_links symlinks, $sz | ${mins} min"
  [ "$n_links" != 0 ] && echo "!!! [$id] export contains symlinks — that violates the hard-copy requirement."
  [ $rel_rc -ne 0 ] && return 2
  return 0
}

STAMP=$(date +%Y%m%dT%H%M%S)
MAIN_LOG=$LOGS/${DAY}_$STAMP.log
{
say "DAY-1 CHUNKED RUN  ($STAMP)  chunks: ${CHUNKS[*]}"
echo "substrate: $DHAKASCENES_SUBSTRATE   VLM_CHECK=${VLM_CHECK:-<default 0>}   VLM_USE_CHECKED=${VLM_USE_CHECKED:-<default 0>}"
echo "log      : $MAIN_LOG"
RESULTS=()
for id in "${CHUNKS[@]}"; do
  run_chunk "$id" 2>&1 | tee -a "$LOGS/chunk_$id.log"
  rc=${PIPESTATUS[0]}
  RESULTS+=("chunk_$id rc=$rc")
  if [ "$rc" = 1 ]; then
    echo "!!! chunk_$id: core chain failed. Not starting the next chunk on a broken profile/config."
    break
  fi
done
say "DONE"
printf '  %s\n' "${RESULTS[@]}"
} 2>&1 | tee -a "$MAIN_LOG"
